name: vendability
favicon: null
layout_spectrum: 0.7129267121199518
typography_spectrum: 0.0205403717700392
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5022402626927942
  lightness: 0.17258282215334475
  saturation: 0.6997565655037761
  rhythmicContrast: 0.5906040626578033
purpose: []
