name: vendability
favicon: null
layout_spectrum: 0.81407
typography_spectrum: 0.0205403717700392
title: The art of online retail
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
